# Generated by Django 5.2.4 on 2026-06-18 13:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_alter_project_created_at_alter_project_github_url_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name": "Проект", "verbose_name_plural": "Проекты"},
        ),
    ]
