# Generated by Django 5.2.4 on 2026-06-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_alter_project_options"),
        ("users", "0004_alter_user_options_remove_user_favorites_projects_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="favorites",
            field=models.ManyToManyField(
                blank=True, related_name="favoritied_by", to="projects.project"
            ),
        ),
    ]
