# Generated by Django 5.2.4 on 2026-06-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_alter_project_options"),
        ("users", "0005_alter_user_favorites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="favorites",
            field=models.ManyToManyField(
                blank=True, related_name="favorited_by", to="projects.project"
            ),
        ),
    ]
